### ISSUE TITLE
Несколько проблем в установке и использовании

### ISSUE THREAD

**Issue by yuri-pechatnov** [avp-avp/rfsniffer#2]
I) В первый раз у меня получилось установить, но было две проблемы
1) lib/libutils/thread.h где-то инклудился как Thread.h
Это в ветке master
Отсюда вопрос, как установить стабильную рабочую версию?
2) После исправления имени файла, удалось создать бинарник
Проверил работу с датчиком Oregon. Работает нормально, в логах есть данные с датчика. Но файл устройства я не нашел. Где он лежит?

II) Потом мне понадобилось пересобрать проект. По неизвестной мне причине, это не получилось
Последовательность действий:
Установил autoconf и libtool
git submodule init
git submodule update --remote
С этим все нормально.
А вот autoreconf -fvi падает с ошибкой:
root@wbdevenv:(...)# autoreconf -fvi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
.ibtoolize: AC_CONFIG_MACRO_DIR([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4
autoreconf: libtoolize failed with exit status: 1
root@wbdevenv:/home/ura/wirenboard/rfsniffer/rfsniffer# autoreconf -fvi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
.ibtoolize: AC_CONFIG_MACRO_DIR([m4]) conflicts with ACLOCAL_AMFLAGS=-I m4
autoreconf: libtoolize failed with exit status: 1

В чем может быть причина?

**Comment by avp-avp** [comment]
I.1) Можно пример файла? В master стабильная версия, которая у меня работает уже довольно давно. Попробую выгрузить "вчистую" и собрать на всякий случай. 
I.2) Что значит файл устройства? Данные датчиков публикуются в mqtt как WB устройства. У Вас должны были появится устройства типа https://www.dropbox.com/s/b9y19irjjv3rxes/Screenshot%202016-09-23%2009.12.48.png?dl=0

II. Странно, я собираю в Вашем контейнере и reconf выглядит
`root@wbdevenv:/home/avp/Projects/wb/rfsniffer# autoreconf -fvi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
`

**Comment by avp-avp** [comment]
`Thread.h` нашел в тестах. Это косяк докера под macos. gcc непринужденно инлудит файлы не попадающие в регистр (

**Comment by yuri-pechatnov** [comment]
Все получилось) Получившаяся чуть более подробная инструкция:
Убедиться, что в git настроены правильные переводы строк! (https://git-scm.com/book/ru/v1/Настройка-Git-Конфигурирование-Git)
git clone https://github.com/avp-avp/rfsniffer.git
cd rfsniffer
git submodule init
git submodule update (если здесь вылетает, нужно настроить ключи ssh: https://help.github.com/articles/generating-an-ssh-key/)
autoreconf -fvi
Дальше используя qemu environment в wbdev:
./configure 
make
Готово!
